name: CI

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        
    - name: Build and test with Maven
      run: mvn test
      
    - name: Check code formatting
      uses: diffplug/spotless-action@v3
      with:
        spotless-version: '5.14.0'
        spotless-files: '**/*.java'
        
    - name: Check PR title
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        pattern: 'PTX-\d+: .*'
