name: CI

on:
  pull_request:
    types: [opened, edited, synchronize]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run tests
        run: mvn test

      - name: Format code
        uses: diffplug/spotless-github-action@v4.5
        with:
          spotless-version: '5.14.2'

      - name: Check PR title format
        uses: peter-evans/regex-check@v1
        with:
          regex: 'PTX-\d+: .+'
          flags: 'i'
          error-message: 'Please follow the PTX-<number>: <title> format in your PR title.'
