name: CI

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check_title:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Check PR Title
      uses: marocchino/sticky-pull-request-comment@v2.4.1
      with:
        message: |
          Please make sure your PR title matches the following format: `PTX-<any string>: <title>`
        regex: 'PTX-\S+: .+'
        exclude: 'automated'

