name: CI
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Build and test with Maven
      run: mvn test

    - name: Code formatting using spotless
      run: |
        mvn spotless:apply
