name: CI
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Code formatting using spotless
      run: mvn spotless:apply

